version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd pre-project-server
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./pre-project-server/build/libs/*.jar)
artifacts:
  files:
    - pre-project-server/build/libs/*.jar
    - pre-project-server/scripts/**
    - pre-project-server/appspec.yml
  discard-paths: yes